function [out,Qmax] = solve_steady_comsol_3D(q,r,lambda,mu,kp,km,alpha,beta,gamma,kappa,Pe,rho,H_3,amp)
%
% temp.m
%
% Model exported on Sep 18 2020, 12:36 by COMSOL 5.5.0.359.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.label('model.mph');

model.baseSystem('none');

model.param.set('q', num2str(q));
model.param.set('r', num2str(r));
model.param.set('lambda', num2str(lambda));
model.param.set('mu', num2str(mu));
model.param.set('kp', num2str(kp));
model.param.set('km', num2str(km));
model.param.set('alpha', num2str(alpha));
model.param.set('beta', num2str(beta));
model.param.set('gamma', num2str(gamma));
model.param.set('kappa', num2str(kappa));
model.param.set('Pe', num2str(Pe));
model.param.set('rho', num2str(rho));
model.param.set('H_3', num2str(H_3));
model.param.set('amp', num2str(amp));

model.component.create('comp2', true);

model.component('comp2').geom.create('geom2', 3);

model.component('comp2').mesh.create('mesh2');

model.component('comp2').geom('geom2').create('wp1', 'WorkPlane');
model.component('comp2').geom('geom2').feature('wp1').set('unite', true);
model.component('comp2').geom('geom2').feature('wp1').geom.create('ls1', 'LineSegment');
model.component('comp2').geom('geom2').feature('wp1').geom.feature('ls1').set('specify1', 'coord');
model.component('comp2').geom('geom2').feature('wp1').geom.feature('ls1').set('coord1', [0 10]);
model.component('comp2').geom('geom2').feature('wp1').geom.feature('ls1').set('specify2', 'coord');
model.component('comp2').geom('geom2').feature('wp1').geom.feature('ls1').set('coord2', [10 10]);
model.component('comp2').geom('geom2').feature('wp1').geom.create('ls2', 'LineSegment');
model.component('comp2').geom('geom2').feature('wp1').geom.feature('ls2').set('specify1', 'coord');
model.component('comp2').geom('geom2').feature('wp1').geom.feature('ls2').set('specify2', 'coord');
model.component('comp2').geom('geom2').feature('wp1').geom.feature('ls2').set('coord2', [0 10]);
model.component('comp2').geom('geom2').feature('wp1').geom.create('ls3', 'LineSegment');
model.component('comp2').geom('geom2').feature('wp1').geom.feature('ls3').set('specify1', 'coord');
model.component('comp2').geom('geom2').feature('wp1').geom.feature('ls3').set('coord1', [10 0]);
model.component('comp2').geom('geom2').feature('wp1').geom.feature('ls3').set('specify2', 'coord');
model.component('comp2').geom('geom2').feature('wp1').geom.feature('ls3').set('coord2', [10 10]);
model.component('comp2').geom('geom2').feature('wp1').geom.create('pc1', 'ParametricCurve');
model.component('comp2').geom('geom2').feature('wp1').geom.feature('pc1').set('parmax', 10);
model.component('comp2').geom('geom2').feature('wp1').geom.feature('pc1').set('coord', {'s' 'amp*(-1+(cos(4*pi*s/10))^2)'});
model.component('comp2').geom('geom2').feature('wp1').geom.create('csol1', 'ConvertToSolid');
model.component('comp2').geom('geom2').feature('wp1').geom.feature('csol1').selection('input').set({'ls1' 'ls2' 'ls3' 'pc1'});
model.component('comp2').geom('geom2').create('ext1', 'Extrude');
model.component('comp2').geom('geom2').feature('ext1').set('inputhandling', 'keep');
model.component('comp2').geom('geom2').feature('ext1').selection('input').set({'wp1'});
model.component('comp2').geom('geom2').feature('ext1').setIndex('distance', 'H_3', 0);
model.component('comp2').geom('geom2').create('ext2', 'Extrude');
model.component('comp2').geom('geom2').feature('ext2').set('reverse', true);
model.component('comp2').geom('geom2').feature('ext2').selection('input').set({'wp1'});
model.component('comp2').geom('geom2').create('blk3', 'Block');
model.component('comp2').geom('geom2').feature('blk3').set('pos', [-5 0 0]);
model.component('comp2').geom('geom2').feature('blk3').set('size', {'5' '10' 'H_3'});
model.component('comp2').geom('geom2').create('blk4', 'Block');
model.component('comp2').geom('geom2').feature('blk4').set('pos', [10 0 0]);
model.component('comp2').geom('geom2').feature('blk4').set('size', {'5' '10' 'H_3'});
model.component('comp2').geom('geom2').run;
model.component('comp2').geom('geom2').run('fin');

model.frame('material1').tag('material2');
model.frame('mesh1').tag('mesh2');
model.frame('geometry1').tag('geometry2');
model.frame('spatial1').tag('spatial2');

model.variable.create('var1');
model.component('comp2').variable.create('var2');
model.component('comp2').variable('var2').set('u2', 'u');
model.component('comp2').variable('var2').set('v2', 'v');
model.component('comp2').variable('var2').set('w2', 'w');
model.component('comp2').variable('var2').selection.geom('geom2', 3);
model.component('comp2').variable('var2').selection.set([1 3 4]);
model.component('comp2').variable.create('var3');
model.component('comp2').variable('var3').set('u2', '0');
model.component('comp2').variable('var3').set('v2', '0');
model.component('comp2').variable('var3').set('w2', '0');
model.component('comp2').variable('var3').selection.geom('geom2', 3);
model.component('comp2').variable('var3').selection.set([2]);

model.component('comp2').view('view2').tag('view21');
model.component('comp2').view('view1').tag('view2');
model.component('comp2').view('view21').tag('view3');
model.view.create('view4', 2);
model.view.create('view5', 2);

model.component('comp2').coordSystem('sys1').tag('sys2');

model.component('comp2').physics.create('spf2', 'LaminarFlow', 'geom2');
model.component('comp2').physics('spf2').identifier('spf2');
model.component('comp2').physics('spf2').selection.set([1 3 4]);
model.component('comp2').physics('spf2').create('inl1', 'InletBoundary', 2);
model.component('comp2').physics('spf2').feature('inl1').selection.set([1]);
model.component('comp2').physics('spf2').create('out1', 'OutletBoundary', 2);
model.component('comp2').physics('spf2').feature('out1').selection.set([21]);
model.component('comp2').physics('spf2').create('sym1', 'Symmetry', 2);
model.component('comp2').physics('spf2').feature('sym1').selection.set([5 14 20]);
model.component('comp2').physics.create('tds2', 'DilutedSpecies', 'geom2');
model.component('comp2').physics('tds2').identifier('tds2');
model.component('comp2').physics('tds2').field('concentration').field('Q');
model.component('comp2').physics('tds2').field('concentration').component({'Q'});
model.component('comp2').physics('tds2').create('conc2', 'Concentration', 2);
model.component('comp2').physics('tds2').feature('conc2').selection.set([1]);
model.component('comp2').physics('tds2').create('reac1', 'Reactions', 3);
model.component('comp2').physics('tds2').feature('reac1').selection.set([2]);
model.component('comp2').physics.create('tds', 'DilutedSpecies', 'geom2');
model.component('comp2').physics('tds').field('concentration').field('I');
model.component('comp2').physics('tds').field('concentration').component({'I'});
model.component('comp2').physics('tds').selection.set([2]);
model.component('comp2').physics('tds').create('reac1', 'Reactions', 3);
model.component('comp2').physics('tds').feature('reac1').selection.set([2]);
model.component('comp2').physics.create('tds3', 'DilutedSpecies', 'geom2');
model.component('comp2').physics('tds3').field('concentration').field('R');
model.component('comp2').physics('tds3').field('concentration').component({'R'});
model.component('comp2').physics('tds3').selection.set([2]);
model.component('comp2').physics('tds3').create('reac1', 'Reactions', 3);
model.component('comp2').physics('tds3').feature('reac1').selection.set([2]);
model.component('comp2').physics.create('tds4', 'DilutedSpecies', 'geom2');
model.component('comp2').physics('tds4').field('concentration').field('C');
model.component('comp2').physics('tds4').field('concentration').component({'C'});
model.component('comp2').physics('tds4').selection.set([2]);
model.component('comp2').physics('tds4').create('reac1', 'Reactions', 3);
model.component('comp2').physics('tds4').feature('reac1').selection.set([2]);

model.component('comp2').mesh('mesh2').create('size1', 'Size');
model.component('comp2').mesh('mesh2').create('size2', 'Size');
model.component('comp2').mesh('mesh2').create('ftet1', 'FreeTet');
model.component('comp2').mesh('mesh2').create('ref1', 'Refine');
model.component('comp2').mesh('mesh2').feature('size1').selection.geom('geom2', 3);
model.component('comp2').mesh('mesh2').feature('size1').selection.set([1 3 4]);
model.component('comp2').mesh('mesh2').feature('size2').selection.geom('geom2', 3);
model.component('comp2').mesh('mesh2').feature('size2').selection.set([2]);

model.component('comp2').view('view2').label('View 2.1');
model.component('comp2').view('view2').set('showgrid', false);
model.component('comp2').view('view2').set('showaxisorientation', false);
model.component('comp2').view('view3').label('View 3');
model.component('comp2').view('view3').axis.set('xmin', 0.2573528289794922);
model.component('comp2').view('view3').axis.set('xmax', 4.801469802856445);
model.component('comp2').view('view3').axis.set('ymin', -2.8785297870635986);
model.component('comp2').view('view3').axis.set('ymax', 1.0402936935424805);
model.view('view4').axis.set('xmin', -5.40000057220459);
model.view('view4').axis.set('xmax', 11.40000057220459);
model.view('view4').axis.set('ymin', -4.268446922302246);
model.view('view4').axis.set('ymax', 6.768446922302246);
model.view('view5').axis.set('xmin', -1.6917810440063477);
model.view('view5').axis.set('xmax', 6.000256538391113);
model.view('view5').axis.set('ymin', -3.1333506107330322);
model.view('view5').axis.set('ymax', 3.1333506107330322);

model.component('comp2').coordSystem('sys2').label('Boundary System 2');
model.component('comp2').coordSystem('sys2').set('name', 'sys2');

model.component('comp2').physics('spf2').label('Laminar Flow');
model.component('comp2').physics('spf2').prop('PhysicalModelProperty').set('Tref', 1);
model.component('comp2').physics('spf2').prop('PhysicalModelProperty').set('pref', 0);
model.component('comp2').physics('spf2').feature('fp1').set('rho_mat', 'userdef');
model.component('comp2').physics('spf2').feature('fp1').set('rho', '0.25');
model.component('comp2').physics('spf2').feature('fp1').set('mu_mat', 'userdef');
model.component('comp2').physics('spf2').feature('fp1').set('mu', 1);
model.component('comp2').physics('spf2').feature('init1').set('u_init', {'y-1'; '0'; '0'});
model.component('comp2').physics('spf2').feature('inl1').set('BoundaryCondition', 'Pressure');
model.component('comp2').physics('spf2').feature('inl1').set('U0in', 'y-1');
model.component('comp2').physics('spf2').feature('inl1').set('u0', {'y-1'; '0'; '0'});
model.component('comp2').physics('spf2').feature('inl1').set('p0', '20/5*1.2');
model.component('comp2').physics('spf2').feature('inl1').set('IT', 'spf.IT_init');
model.component('comp2').physics('spf2').feature('inl1').set('LT', 'spf.LT_init');
model.component('comp2').physics('spf2').feature('inl1').set('k0', 'spf.k0_init');
model.component('comp2').physics('spf2').feature('inl1').set('ep0', 'spf.ep0_init');
model.component('comp2').physics('spf2').feature('inl1').set('om0', 'spf.om0_init');
model.component('comp2').physics('spf2').feature('inl1').set('nutilde0', '3*spf.nu');
model.component('comp2').physics('spf2').feature('inl1').set('zeta0', 'spf.zeta0_init');
model.component('comp2').physics('spf2').feature('inl1').set('alpha0', 'spf.alpha0_init');
model.component('comp2').physics('spf2').feature('out1').set('NormalFlow', true);
model.component('comp2').physics('tds2').prop('MassConsistentStabilization').set('glim_mass', '0.1[mol/m^3]/tds2.helem');
model.component('comp2').physics('tds2').feature('cdm1').set('u', {'Pe*u2'; 'Pe*v2'; 'Pe*w2'});
model.component('comp2').physics('tds2').feature('cdm1').set('D_Q', [1; 0; 0; 0; 1; 0; 0; 0; 1]);
model.component('comp2').physics('tds2').feature('init1').set('initc', 'Q');
model.component('comp2').physics('tds2').feature('conc2').set('species', true);
model.component('comp2').physics('tds2').feature('reac1').set('R_Q', 'rho*(q+lambda*I-(kp)*Q*R + km*C) - kappa*Q');
model.component('comp2').physics('tds').feature('cdm1').set('D_I', [0; 0; 0; 0; 0; 0; 0; 0; 0]);
model.component('comp2').physics('tds').feature('init1').set('initc', 'I');
model.component('comp2').physics('tds').feature('reac1').set('R_I', 'mu*C-alpha*I');
model.component('comp2').physics('tds3').feature('cdm1').set('D_R', [0; 0; 0; 0; 0; 0; 0; 0; 0]);
model.component('comp2').physics('tds3').feature('init1').set('initc', 'R');
model.component('comp2').physics('tds3').feature('reac1').set('R_R', 'r - (kp)*Q*R + km*C - beta*R');
model.component('comp2').physics('tds4').feature('cdm1').set('D_C', [0; 0; 0; 0; 0; 0; 0; 0; 0]);
model.component('comp2').physics('tds4').feature('init1').set('initc', 'C');
model.component('comp2').physics('tds4').feature('reac1').set('R_C', 'kp*Q*R - km*C - gamma*C');

model.component('comp2').physics('tds2').create('reac2', 'Reactions', 3);
model.component('comp2').physics('tds2').feature('reac2').selection.set([1 3 4]);
model.component('comp2').physics('tds2').feature('reac2').setIndex('R_Q', '-kappa*Q', 0);

model.component('comp2').mesh('mesh2').feature('size').set('hauto', 5);
model.component('comp2').mesh('mesh2').feature('size').set('table', 'cfd');
model.component('comp2').mesh('mesh2').feature('size1').set('hauto', 6);
model.component('comp2').mesh('mesh2').feature('size1').set('table', 'cfd');
model.component('comp2').mesh('mesh2').feature('size2').set('hauto', 3);
model.component('comp2').mesh('mesh2').feature('size2').set('table', 'cfd');
model.component('comp2').mesh('mesh2').feature('ftet1').set('zscale', 2);
model.component('comp2').mesh('mesh2').feature('ref1').set('boxcoord', true);
model.component('comp2').mesh('mesh2').feature('ref1').set('xmax', 10);
model.component('comp2').mesh('mesh2').feature('ref1').set('xmin', -10);
model.component('comp2').mesh('mesh2').feature('ref1').set('ymax', 10);
model.component('comp2').mesh('mesh2').feature('ref1').set('ymin', -5);
model.component('comp2').mesh('mesh2').feature('ref1').set('zmax', 1);
model.component('comp2').mesh('mesh2').feature('ref1').set('zmin', -1);
model.component('comp2').mesh('mesh2').run;

model.study.create('std1');
model.study('std1').create('stat', 'Stationary');
model.study('std1').feature('stat').set('activate', {'spf2' 'on' 'tds2' 'off' 'tds' 'off' 'tds3' 'off' 'tds4' 'off'  ...
'frame:spatial2' 'on' 'frame:material2' 'on'});
model.study.create('std2');
model.study('std2').create('stat', 'Stationary');
model.study('std2').feature('stat').set('activate', {'spf2' 'off' 'tds2' 'on' 'tds' 'on' 'tds3' 'on' 'tds4' 'on'  ...
'frame:spatial2' 'on' 'frame:material2' 'on'});
model.study.create('std3');
model.study('std3').create('time', 'Transient');
model.study('std3').feature('time').set('activate', {'spf2' 'off' 'tds2' 'on' 'tds' 'on' 'tds3' 'on' 'tds4' 'on'  ...
'frame:spatial2' 'on' 'frame:material2' 'on'});

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').attach('std1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('sc1', 'SCGS');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('sc1', 'SCGS');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature.remove('fcDef');
model.sol.create('sol2');
model.sol('sol2').study('std2');
model.sol('sol2').attach('std2');
model.sol('sol2').create('st1', 'StudyStep');
model.sol('sol2').create('v1', 'Variables');
model.sol('sol2').create('s1', 'Stationary');
model.sol('sol2').feature('s1').create('se1', 'Segregated');
model.sol('sol2').feature('s1').create('i1', 'Iterative');
model.sol('sol2').feature('s1').create('i2', 'Iterative');
model.sol('sol2').feature('s1').create('i3', 'Iterative');
model.sol('sol2').feature('s1').create('i4', 'Iterative');
model.sol('sol2').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol2').feature('s1').feature('se1').create('ss1', 'SegregatedStep');
model.sol('sol2').feature('s1').feature('se1').create('ss2', 'SegregatedStep');
model.sol('sol2').feature('s1').feature('se1').create('ss3', 'SegregatedStep');
model.sol('sol2').feature('s1').feature('se1').create('ss4', 'SegregatedStep');
model.sol('sol2').feature('s1').feature('se1').feature.remove('ssDef');
model.sol('sol2').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol2').feature('s1').feature('i1').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol2').feature('s1').feature('i1').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol2').feature('s1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol2').feature('s1').feature('i2').create('mg1', 'Multigrid');
model.sol('sol2').feature('s1').feature('i2').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol2').feature('s1').feature('i2').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol2').feature('s1').feature('i2').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol2').feature('s1').feature('i3').create('mg1', 'Multigrid');
model.sol('sol2').feature('s1').feature('i3').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol2').feature('s1').feature('i3').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol2').feature('s1').feature('i3').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol2').feature('s1').feature('i4').create('mg1', 'Multigrid');
model.sol('sol2').feature('s1').feature('i4').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol2').feature('s1').feature('i4').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol2').feature('s1').feature('i4').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol2').feature('s1').feature.remove('fcDef');
model.sol.create('sol6');
model.sol('sol6').study('std3');
model.sol('sol6').attach('std3');
model.sol('sol6').create('st1', 'StudyStep');
model.sol('sol6').create('v1', 'Variables');
model.sol('sol6').create('t1', 'Time');
model.sol('sol6').feature('t1').create('se1', 'Segregated');
model.sol('sol6').feature('t1').create('i1', 'Iterative');
model.sol('sol6').feature('t1').create('i2', 'Iterative');
model.sol('sol6').feature('t1').create('i3', 'Iterative');
model.sol('sol6').feature('t1').create('i4', 'Iterative');
model.sol('sol6').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol6').feature('t1').feature('se1').create('ss1', 'SegregatedStep');
model.sol('sol6').feature('t1').feature('se1').create('ss2', 'SegregatedStep');
model.sol('sol6').feature('t1').feature('se1').create('ss3', 'SegregatedStep');
model.sol('sol6').feature('t1').feature('se1').create('ss4', 'SegregatedStep');
model.sol('sol6').feature('t1').feature('se1').feature.remove('ssDef');
model.sol('sol6').feature('t1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol6').feature('t1').feature('i1').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol6').feature('t1').feature('i1').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol6').feature('t1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol6').feature('t1').feature('i2').create('mg1', 'Multigrid');
model.sol('sol6').feature('t1').feature('i2').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol6').feature('t1').feature('i2').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol6').feature('t1').feature('i2').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol6').feature('t1').feature('i3').create('mg1', 'Multigrid');
model.sol('sol6').feature('t1').feature('i3').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol6').feature('t1').feature('i3').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol6').feature('t1').feature('i3').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol6').feature('t1').feature('i4').create('mg1', 'Multigrid');
model.sol('sol6').feature('t1').feature('i4').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol6').feature('t1').feature('i4').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol6').feature('t1').feature('i4').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol6').feature('t1').feature.remove('fcDef');

model.result.dataset.create('dset5', 'Solution');
model.result.dataset.create('cpl1', 'CutPlane');
model.result.dataset.create('cln1', 'CutLine3D');
model.result.dataset.create('dset6', 'Solution');
model.result.dataset.create('dset8', 'Solution');
model.result.dataset.create('cln2', 'CutLine3D');
model.result.dataset.create('cln3', 'CutLine3D');
model.result.dataset.create('cln4', 'CutLine3D');
model.result.dataset.create('cln5', 'CutLine3D');
model.result.dataset('cpl1').set('data', 'dset5');
model.result.dataset('cln1').set('data', 'dset6');
model.result.dataset('dset6').set('solution', 'sol2');
model.result.dataset('dset8').set('solution', 'sol6');
model.result.dataset('cln2').set('data', 'dset6');
model.result.dataset('cln3').set('data', 'dset6');
model.result.dataset('cln4').set('data', 'dset6');
model.result.dataset('cln5').set('data', 'dset6');
model.result.dataset.remove('dset1');
model.result.dataset.remove('dset2');
model.result.dataset.remove('dset3');
model.result.numerical.create('max1', 'MaxVolume');
model.result.numerical('max1').set('data', 'dset6');
model.result.numerical('max1').selection.set([2]);
model.result.numerical('max1').set('probetag', 'none');
model.result.create('pg17', 'PlotGroup3D');
model.result.create('pg18', 'PlotGroup3D');
model.result.create('pg19', 'PlotGroup1D');
model.result.create('pg39', 'PlotGroup1D');
model.result.create('pg20', 'PlotGroup3D');
model.result.create('pg21', 'PlotGroup3D');
model.result.create('pg22', 'PlotGroup3D');
model.result('pg17').create('surf1', 'Surface');
model.result('pg17').feature('surf1').set('expr', 'spf2.sr');
model.result('pg18').create('slc1', 'Slice');
model.result('pg18').feature('slc1').set('expr', 'u');
model.result('pg19').create('lngr1', 'LineGraph');
model.result('pg19').create('lngr2', 'LineGraph');
model.result('pg19').create('lngr3', 'LineGraph');
model.result('pg19').create('lngr4', 'LineGraph');
model.result('pg19').create('lngr5', 'LineGraph');
model.result('pg19').feature('lngr1').set('xdata', 'expr');
model.result('pg19').feature('lngr1').set('expr', '(-Qz/Q)');
model.result('pg19').feature('lngr2').set('xdata', 'expr');
model.result('pg19').feature('lngr2').set('expr', '((spf2.sr)/2 * Pe )^(1/3) * (3^(2/3)/(2.6789*x^(1/3)))');
model.result('pg19').feature('lngr3').set('xdata', 'expr');
model.result('pg19').feature('lngr3').set('expr', '-Qz/Q');
model.result('pg19').feature('lngr4').set('xdata', 'expr');
model.result('pg19').feature('lngr4').set('expr', '(-Qz/Q)');
model.result('pg19').feature('lngr5').set('xdata', 'expr');
model.result('pg19').feature('lngr5').set('expr', '(-Qz/Q)');
model.result('pg39').create('lngr1', 'LineGraph');
model.result('pg39').create('lngr2', 'LineGraph');
model.result('pg39').feature('lngr1').set('xdata', 'expr');
model.result('pg39').feature('lngr1').set('expr', '-Qz/Q');
model.result('pg39').feature('lngr2').set('xdata', 'expr');
model.result('pg39').feature('lngr2').set('expr', 'x^(-1/3)');
model.result('pg20').set('data', 'dset6');
model.result('pg20').create('slc1', 'Slice');
model.result('pg20').feature('slc1').set('expr', 'u');
model.result('pg21').set('data', 'dset6');
model.result('pg21').create('slc1', 'Slice');
model.result('pg21').feature('slc1').set('expr', 'spf2.sr');
model.result('pg22').set('data', 'dset8');
model.result('pg22').create('surf1', 'Surface');
model.result('pg22').feature('surf1').set('expr', 'Q');

model.study('std1').label('Flow Solver');
model.study('std1').feature('stat').set('ngen', 2);
model.study('std2').label('Steady QS solver 1');
model.study('std2').feature('stat').set('useinitsol', true);
model.study('std2').feature('stat').set('initmethod', 'sol');
model.study('std2').feature('stat').set('initstudy', 'std3');
model.study('std2').feature('stat').set('solnum', 'last');
model.study('std2').feature('stat').set('usesol', true);
model.study('std2').feature('stat').set('notsolmethod', 'sol');
model.study('std2').feature('stat').set('notstudy', 'std1');
model.study('std2').feature('stat').set('notsolnum', 'auto');
model.study('std2').feature('stat').set('ngen', 2);
model.study('std3').label('Unsteady QS solver');
model.study('std3').feature('time').set('tlist', 'range(0,1e7,1e7)');
model.study('std3').feature('time').set('useinitsol', true);
model.study('std3').feature('time').set('usesol', true);
model.study('std3').feature('time').set('notsolmethod', 'sol');
model.study('std3').feature('time').set('notstudy', 'std1');
model.study('std3').feature('time').set('notsolnum', 'auto');

model.sol('sol1').attach('std1');
model.sol('sol1').feature('s1').feature('aDef').set('cachepattern', true);
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'i1');
model.sol('sol1').feature('s1').feature('fc1').set('initstep', 0.01);
model.sol('sol1').feature('s1').feature('fc1').set('maxiter', 100);
model.sol('sol1').feature('s1').feature('i1').label('AMG, fluid flow variables (spf2)');
model.sol('sol1').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol1').feature('s1').feature('i1').set('maxlinit', 200);
model.sol('sol1').feature('s1').feature('i1').set('rhob', 20);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('prefun', 'saamg');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('maxcoarsedof', 80000);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('strconn', 0.02);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('saamgcompwise', true);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('usesmooth', false);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sc1').set('linesweeptype', 'ssor');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sc1').set('iter', 0);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sc1').set('scgsvertexrelax', 0.7);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('sc1').set('linesweeptype', 'ssor');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('sc1').set('iter', 1);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('sc1').set('scgsvertexrelax', 0.7);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol1').feature('s1').feature('d1').label('Direct, fluid flow variables (spf2)');
model.sol('sol1').feature('s1').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('s1').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol1').runAll;
model.sol('sol6').attach('std3');
model.sol('sol6').feature('v1').set('notsolmethod', 'sol');
model.sol('sol6').feature('v1').set('notsol', 'sol1');
model.sol('sol6').feature('v1').set('notsolnum', 'auto');
model.sol('sol6').feature('v1').set('clist', {'range(0,1e7,1e7)' '1000.0[s]'});
model.sol('sol6').feature('t1').set('control', 'user');
model.sol('sol6').feature('t1').set('tlist', 'range(0,1e7,1e7)');
model.sol('sol6').feature('t1').set('rtol', 0.005);
model.sol('sol6').feature('t1').set('maxorder', 2);
model.sol('sol6').feature('t1').feature('dDef').set('linsolver', 'pardiso');
model.sol('sol6').feature('t1').feature('se1').active(false);
model.sol('sol6').feature('t1').feature('se1').feature('ss1').label('Concentration I');
model.sol('sol6').feature('t1').feature('se1').feature('ss1').set('segvar', {'comp2_I'});
model.sol('sol6').feature('t1').feature('se1').feature('ss1').set('linsolver', 'i1');
model.sol('sol6').feature('t1').feature('se1').feature('ss1').set('subdamp', 0.8);
model.sol('sol6').feature('t1').feature('se1').feature('ss1').set('subjtech', 'once');
model.sol('sol6').feature('t1').feature('se1').feature('ss2').label('Concentration Q');
model.sol('sol6').feature('t1').feature('se1').feature('ss2').set('segvar', {'comp2_Q'});
model.sol('sol6').feature('t1').feature('se1').feature('ss2').set('linsolver', 'i2');
model.sol('sol6').feature('t1').feature('se1').feature('ss2').set('subdamp', 0.8);
model.sol('sol6').feature('t1').feature('se1').feature('ss2').set('subjtech', 'once');
model.sol('sol6').feature('t1').feature('se1').feature('ss3').label('Concentration R');
model.sol('sol6').feature('t1').feature('se1').feature('ss3').set('segvar', {'comp2_R'});
model.sol('sol6').feature('t1').feature('se1').feature('ss3').set('linsolver', 'i3');
model.sol('sol6').feature('t1').feature('se1').feature('ss3').set('subdamp', 0.8);
model.sol('sol6').feature('t1').feature('se1').feature('ss3').set('subjtech', 'once');
model.sol('sol6').feature('t1').feature('se1').feature('ss4').label('Concentration C');
model.sol('sol6').feature('t1').feature('se1').feature('ss4').set('segvar', {'comp2_C'});
model.sol('sol6').feature('t1').feature('se1').feature('ss4').set('linsolver', 'i4');
model.sol('sol6').feature('t1').feature('se1').feature('ss4').set('subdamp', 0.8);
model.sol('sol6').feature('t1').feature('se1').feature('ss4').set('subjtech', 'once');
model.sol('sol6').feature('t1').feature('i1').set('maxlinit', 400);
model.sol('sol6').feature('t1').feature('i1').set('rhob', 40);
model.sol('sol6').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.2);
model.sol('sol6').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('relax', 0.4);
model.sol('sol6').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.2);
model.sol('sol6').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('seconditer', 2);
model.sol('sol6').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('relax', 0.4);
model.sol('sol6').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol6').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol6').feature('t1').feature('i2').set('maxlinit', 400);
model.sol('sol6').feature('t1').feature('i2').set('rhob', 40);
model.sol('sol6').feature('t1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.2);
model.sol('sol6').feature('t1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('relax', 0.4);
model.sol('sol6').feature('t1').feature('i2').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.2);
model.sol('sol6').feature('t1').feature('i2').feature('mg1').feature('po').feature('sl1').set('seconditer', 2);
model.sol('sol6').feature('t1').feature('i2').feature('mg1').feature('po').feature('sl1').set('relax', 0.4);
model.sol('sol6').feature('t1').feature('i2').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol6').feature('t1').feature('i2').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol6').feature('t1').feature('i3').set('maxlinit', 400);
model.sol('sol6').feature('t1').feature('i3').set('rhob', 40);
model.sol('sol6').feature('t1').feature('i3').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.2);
model.sol('sol6').feature('t1').feature('i3').feature('mg1').feature('pr').feature('sl1').set('relax', 0.4);
model.sol('sol6').feature('t1').feature('i3').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.2);
model.sol('sol6').feature('t1').feature('i3').feature('mg1').feature('po').feature('sl1').set('seconditer', 2);
model.sol('sol6').feature('t1').feature('i3').feature('mg1').feature('po').feature('sl1').set('relax', 0.4);
model.sol('sol6').feature('t1').feature('i3').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol6').feature('t1').feature('i3').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol6').feature('t1').feature('i4').set('maxlinit', 400);
model.sol('sol6').feature('t1').feature('i4').set('rhob', 40);
model.sol('sol6').feature('t1').feature('i4').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.2);
model.sol('sol6').feature('t1').feature('i4').feature('mg1').feature('pr').feature('sl1').set('relax', 0.4);
model.sol('sol6').feature('t1').feature('i4').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.2);
model.sol('sol6').feature('t1').feature('i4').feature('mg1').feature('po').feature('sl1').set('seconditer', 2);
model.sol('sol6').feature('t1').feature('i4').feature('mg1').feature('po').feature('sl1').set('relax', 0.4);
model.sol('sol6').feature('t1').feature('i4').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol6').feature('t1').feature('i4').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol6').feature('t1').feature('fc1').active(true);
model.sol('sol6').feature('t1').feature('fc1').set('maxiter', 8);
model.sol('sol6').feature('t1').feature('fc1').set('ntolfact', '1e-2');
model.sol('sol6').runAll;
model.sol('sol2').attach('std2');
model.sol('sol2').feature('v1').set('initmethod', 'sol');
model.sol('sol2').feature('v1').set('initsol', 'sol6');
model.sol('sol2').feature('v1').set('solnum', 'last');
model.sol('sol2').feature('v1').set('notsolmethod', 'sol');
model.sol('sol2').feature('v1').set('notsol', 'sol1');
model.sol('sol2').feature('v1').set('notsolnum', 'auto');
model.sol('sol2').feature('s1').feature('dDef').set('linsolver', 'pardiso');
model.sol('sol2').feature('s1').feature('se1').feature('ss1').active(false);
model.sol('sol2').feature('s1').feature('se1').feature('ss1').label('Concentration I');
model.sol('sol2').feature('s1').feature('se1').feature('ss1').set('segvar', {'comp2_I'});
model.sol('sol2').feature('s1').feature('se1').feature('ss1').set('linsolver', 'i1');
model.sol('sol2').feature('s1').feature('se1').feature('ss1').set('subdamp', 0.5);
model.sol('sol2').feature('s1').feature('se1').feature('ss2').active(false);
model.sol('sol2').feature('s1').feature('se1').feature('ss2').label('Concentration Q');
model.sol('sol2').feature('s1').feature('se1').feature('ss2').set('segvar', {'comp2_Q'});
model.sol('sol2').feature('s1').feature('se1').feature('ss2').set('linsolver', 'i2');
model.sol('sol2').feature('s1').feature('se1').feature('ss2').set('subdamp', 0.5);
model.sol('sol2').feature('s1').feature('se1').feature('ss3').active(false);
model.sol('sol2').feature('s1').feature('se1').feature('ss3').label('Concentration R');
model.sol('sol2').feature('s1').feature('se1').feature('ss3').set('segvar', {'comp2_R'});
model.sol('sol2').feature('s1').feature('se1').feature('ss3').set('linsolver', 'i3');
model.sol('sol2').feature('s1').feature('se1').feature('ss3').set('subdamp', 0.5);
model.sol('sol2').feature('s1').feature('se1').feature('ss4').active(false);
model.sol('sol2').feature('s1').feature('se1').feature('ss4').label('Concentration C');
model.sol('sol2').feature('s1').feature('se1').feature('ss4').set('segvar', {'comp2_C'});
model.sol('sol2').feature('s1').feature('se1').feature('ss4').set('linsolver', 'i4');
model.sol('sol2').feature('s1').feature('se1').feature('ss4').set('subdamp', 0.5);
model.sol('sol2').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol2').feature('s1').feature('i1').set('maxlinit', 400);
model.sol('sol2').feature('s1').feature('i1').set('rhob', 40);
model.sol('sol2').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.2);
model.sol('sol2').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('relax', 0.4);
model.sol('sol2').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.2);
model.sol('sol2').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('seconditer', 2);
model.sol('sol2').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('relax', 0.4);
model.sol('sol2').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol2').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol2').feature('s1').feature('i2').set('nlinnormuse', true);
model.sol('sol2').feature('s1').feature('i2').set('maxlinit', 400);
model.sol('sol2').feature('s1').feature('i2').set('rhob', 40);
model.sol('sol2').feature('s1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.2);
model.sol('sol2').feature('s1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('relax', 0.4);
model.sol('sol2').feature('s1').feature('i2').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.2);
model.sol('sol2').feature('s1').feature('i2').feature('mg1').feature('po').feature('sl1').set('seconditer', 2);
model.sol('sol2').feature('s1').feature('i2').feature('mg1').feature('po').feature('sl1').set('relax', 0.4);
model.sol('sol2').feature('s1').feature('i2').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol2').feature('s1').feature('i2').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol2').feature('s1').feature('i3').set('nlinnormuse', true);
model.sol('sol2').feature('s1').feature('i3').set('maxlinit', 400);
model.sol('sol2').feature('s1').feature('i3').set('rhob', 40);
model.sol('sol2').feature('s1').feature('i3').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.2);
model.sol('sol2').feature('s1').feature('i3').feature('mg1').feature('pr').feature('sl1').set('relax', 0.4);
model.sol('sol2').feature('s1').feature('i3').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.2);
model.sol('sol2').feature('s1').feature('i3').feature('mg1').feature('po').feature('sl1').set('seconditer', 2);
model.sol('sol2').feature('s1').feature('i3').feature('mg1').feature('po').feature('sl1').set('relax', 0.4);
model.sol('sol2').feature('s1').feature('i3').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol2').feature('s1').feature('i3').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol2').feature('s1').feature('i4').set('nlinnormuse', true);
model.sol('sol2').feature('s1').feature('i4').set('maxlinit', 400);
model.sol('sol2').feature('s1').feature('i4').set('rhob', 40);
model.sol('sol2').feature('s1').feature('i4').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.2);
model.sol('sol2').feature('s1').feature('i4').feature('mg1').feature('pr').feature('sl1').set('relax', 0.4);
model.sol('sol2').feature('s1').feature('i4').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.2);
model.sol('sol2').feature('s1').feature('i4').feature('mg1').feature('po').feature('sl1').set('seconditer', 2);
model.sol('sol2').feature('s1').feature('i4').feature('mg1').feature('po').feature('sl1').set('relax', 0.4);
model.sol('sol2').feature('s1').feature('i4').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol2').feature('s1').feature('i4').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol2').feature('s1').feature('fc1').active(true);
model.sol('sol2').feature('s1').feature('fc1').set('maxiter', 50);
model.sol('sol2').feature('s1').feature('fc1').set('ntolfact', '1e-2');
model.sol('sol2').runAll;
model.result.dataset('cpl1').set('quickx', 2);
model.result.dataset('cln1').set('genpoints', [1.25 1 0; 1.25 -2 0]);
model.result.dataset('cln1').set('bndsnap', true);
model.result.dataset('cln2').set('genpoints', [0 0 1; 10 0 1]);
model.result.dataset('cln3').set('genpoints', [3.75 1 0; 3.75 -2 0]);
model.result.dataset('cln3').set('bndsnap', true);
model.result.dataset('cln3').set('spacevars', {'cln1x'});
model.result.dataset('cln4').set('genpoints', [6.25 1 0; 6.25 -2 0]);
model.result.dataset('cln4').set('bndsnap', true);
model.result.dataset('cln4').set('spacevars', {'cln1x'});
model.result.dataset('cln5').set('genpoints', [8.75 1 0; 8.75 -2 0]);
model.result.dataset('cln5').set('bndsnap', true);
model.result.dataset('cln5').set('spacevars', {'cln1x'});
model.result.numerical('max1').set('expr', {'Q'});
model.result.numerical('max1').set('unit', {''});
model.result.numerical('max1').set('descr', {'Concentration'});
model.result('pg17').label('wall shear stress');
model.result('pg17').feature('surf1').set('rangecoloractive', true);
model.result('pg17').feature('surf1').set('rangecolormax', 0.421527169895156);
model.result('pg17').feature('surf1').set('smooth', 'everywhere');
model.result('pg17').feature('surf1').set('recover', 'pprint');
model.result('pg17').feature('surf1').set('resolution', 'normal');
model.result('pg18').label('Flow slices');
model.result('pg18').feature('slc1').set('interactive', true);
model.result('pg18').feature('slc1').set('shift', 0.799999999999999);
model.result('pg18').feature('slc1').set('smooth', 'internal');
model.result('pg18').feature('slc1').set('resolution', 'normal');
model.result('pg19').label('cut line');
model.result('pg19').set('data', 'cln1');
model.result('pg19').set('xlabel', 'y-coordinate');
model.result('pg19').set('xlabelactive', false);
model.result('pg19').feature('lngr1').set('data', 'cln1');
model.result('pg19').feature('lngr1').set('xdataexpr', 'y');
model.result('pg19').feature('lngr1').set('xdatadescr', 'y-coordinate');
model.result('pg19').feature('lngr1').set('resolution', 'norefine');
model.result('pg19').feature('lngr1').set('smooth', 'everywhere');
model.result('pg19').feature('lngr1').set('recover', 'ppr');
model.result('pg19').feature('lngr1').set('resolution', 'norefine');
model.result('pg19').feature('lngr2').set('data', 'cln5');
model.result('pg19').feature('lngr2').set('xdataexpr', 'y');
model.result('pg19').feature('lngr2').set('xdatadescr', 'y-coordinate');
model.result('pg19').feature('lngr2').set('resolution', 'extrafine');
model.result('pg19').feature('lngr2').set('smooth', 'everywhere');
model.result('pg19').feature('lngr2').set('recover', 'pprint');
model.result('pg19').feature('lngr2').set('resolution', 'extrafine');
model.result('pg19').feature('lngr3').set('data', 'cln3');
model.result('pg19').feature('lngr3').set('xdataexpr', 'y');
model.result('pg19').feature('lngr3').set('xdatadescr', 'y-coordinate');
model.result('pg19').feature('lngr3').set('resolution', 'normal');
model.result('pg19').feature('lngr4').set('data', 'cln4');
model.result('pg19').feature('lngr4').set('xdataexpr', 'y');
model.result('pg19').feature('lngr4').set('xdatadescr', 'y-coordinate');
model.result('pg19').feature('lngr4').set('resolution', 'normal');
model.result('pg19').feature('lngr5').set('data', 'cln5');
model.result('pg19').feature('lngr5').set('xdataexpr', 'y');
model.result('pg19').feature('lngr5').set('xdatadescr', 'y-coordinate');
model.result('pg19').feature('lngr5').set('resolution', 'normal');
model.result('pg39').set('data', 'cln2');
model.result('pg39').set('xlabel', 'x-coordinate');
model.result('pg39').set('xlabelactive', false);
model.result('pg39').feature('lngr1').set('xdataexpr', 'x');
model.result('pg39').feature('lngr1').set('xdatadescr', 'x-coordinate');
model.result('pg39').feature('lngr1').set('resolution', 'coarse');
model.result('pg39').feature('lngr1').set('smooth', 'everywhere');
model.result('pg39').feature('lngr1').set('recover', 'ppr');
model.result('pg39').feature('lngr1').set('resolution', 'coarse');
model.result('pg39').feature('lngr2').set('xdataexpr', 'x');
model.result('pg39').feature('lngr2').set('xdatadescr', 'x-coordinate');
model.result('pg39').feature('lngr2').set('resolution', 'coarse');
model.result('pg39').feature('lngr2').set('smooth', 'everywhere');
model.result('pg39').feature('lngr2').set('recover', 'ppr');
model.result('pg39').feature('lngr2').set('resolution', 'coarse');
model.result('pg20').label('Q plane yz');
model.result('pg20').set('edges', false);
model.result('pg20').feature('slc1').set('interactive', true);
model.result('pg20').feature('slc1').set('shift', -3);
model.result('pg20').feature('slc1').set('resolution', 'normal');
model.result('pg21').label('Q plane xz');
model.result('pg21').feature('slc1').set('quickplane', 'zx');
model.result('pg21').feature('slc1').set('quickynumber', 1);
model.result('pg21').feature('slc1').set('interactive', true);
model.result('pg21').feature('slc1').set('rangecoloractive', true);
model.result('pg21').feature('slc1').set('rangecolormax', 0.05);
model.result('pg21').feature('slc1').set('resolution', 'normal');
model.result('pg22').label('surface Q');
model.result('pg22').set('edges', false);
model.result('pg22').feature('surf1').set('titletype', 'none');
model.result('pg22').feature('surf1').set('smooth', 'everywhere');
model.result('pg22').feature('surf1').set('recover', 'ppr');
model.result('pg22').feature('surf1').set('resolution', 'normal');

model.result.table.create('tbl1', 'Table');
model.result.numerical('max1').set('table', 'tbl1');
model.result.numerical('max1').setResult;
Qmax = model.result.table('tbl1').getReal;

out = model;
